# economic inflation analysis

### Author

Jinran Cheng

### Project Objective

The objective of this project is to investigate the relationship between inflation and major economic indicators in Canada.

## Research Question

Which economic indicators are most strongly associated with inflation?

### Technologies Used

- pandas
- numpy
- matplotlib
- scikit-learn
- jupyter

## Economic Indicators

- Consumer Price Index (CPI)
- Inflation Rate
- Unemployment Rate
- Interest Rate
- GDP Growth

## Why This Project Matters

Understanding the relationship between these indicators helps governments, businesses, and economists make informed decisions regarding monetary policy and economic planning.

### Data source

- statistics Canada
- FRED

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("../data/raw/cpi_canada.csv")

In [11]:
df.head()

  observation_date  CPALCY01CAM661N
0       1961-01-01        13.428804
1       1961-02-01        13.428804
2       1961-03-01        13.377873
3       1961-04-01        13.343919
4       1961-05-01        13.259034

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 755 entries, 0 to 754
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  755 non-null    str
 1   CPALCY01CAM661N   755 non-null    float64
dtypes: float64(1), str(1)
memory usage: 11.9 KB

In [5]:
df.describe()

       CPALCY01CAM661N
count       755.000000
mean         61.063693
std          33.139140
min          13.259034
25%          25.422032
50%          68.859678
75%          89.197304
max         126.189364

In [6]:
df.columns

Index(['observation_date', 'CPALCY01CAM661N'], dtype='str')

In [7]:
df.shape

(755, 2)

In [8]:
df.isnull().sum()

observation_date    0
CPALCY01CAM661N     0
dtype: int64

### Initial Data Inspection

In this notebook section, I imported the CPI dataset into pandas and performed an initial inspection.

I used `head()` to preview the first few rows, `info()` to examine the dataset structure, `describe()` to summarize numerical variables, `columns` to identify the available variables, `shape` to determine the dataset dimensions, and `isnull().sum()` to check for missing values.

These steps are essential before performing any statistical analysis because they check potential data quality issues and provide an overview of the dataset.